[fmt]
quote_style = 'single'
single_line_statement_blocks = 'single'

[profile.default]
solc = '0.8.14'
src = 'src'
test = 'src/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'src/test'

[rpc_endpoints]
local = "${LOCAL_RPC}"
mainnet = "${MAINNET_RPC}"
goerli = "${GOERLI_RPC}"